server:
  port: 8083
spring:
  application:
    name: hello-second
eureka:
  client:
    service-url:
      defaultZone:  http://localhost:8761/eureka
  instance:
    instance-id: provider-second
    prefer-ip-address: true

name: mytest——change-6th
age: 24